# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "auto output ipa, upload payer"
  lane :release do
    api_key = "a39a0f089321ef0680a16149b263770e"
    user_key = "60765d6594ae27dd8461dae8967ae99a"
    # xcode打包
    gym(
      clean:true, #打包前clean项目
      export_method: "ad-hoc", #导出方式
      configuration: "Release",#环境
      output_directory:"./build/outputs",#ipa的存放目录
    )
    # 上传蒲公英 插件全局安装
    pgyer(
      update_description: "update by fastlane", 
      api_key: "#{api_key}", 
      user_key: "#{user_key}", 
      install_type: "1"
    )
  end
end
