# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "auto output apk, upload payer"
  lane :release do
    api_key = "a39a0f089321ef0680a16149b263770e"
    user_key = "60765d6594ae27dd8461dae8967ae99a"
    # 不能清除，有些东西需要下载很久才能成功打包apk
    # gradle(task:'clean')
    # 使用gradle命令打包
    # gradle(task: 'assemble', build_type: 'Release')
    # 使用flutter命令打包
    system "flutter build apk"
    path = Dir::getwd
    path = path.chomp("/android/fastlane")
    # 上传蒲公英
    pgyer(
      update_description: "update by fastlane", 
      api_key: "#{api_key}", 
      user_key: "#{user_key}", 
      install_type: "1",
      apk: "#{path}/build/app/outputs/apk/release/app-release.apk"
    )
  end
end
